# Generated by Django 3.0.6 on 2020-05-17 18:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='文章分类', max_length=25, verbose_name='文章分类')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='文章标签')),
                ('desc', models.TextField(max_length=50, verbose_name='标签描述')),
                ('category', models.ForeignKey(help_text='文章分类', on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='文章分类')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(choices=[('yes', '是'), ('no', '否')], default='no', max_length=5, verbose_name='是否置顶')),
                ('title', models.CharField(default='没有标题吖!', max_length=100, verbose_name='标题')),
                ('brief', models.TextField(help_text='简短描述', max_length=500, verbose_name='简短描述')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='正文', verbose_name='正文')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('total_views', models.IntegerField(default=0, verbose_name='访问量')),
                ('category', models.ForeignKey(help_text='文章分类', on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='文章分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-created'],
            },
        ),
    ]
